volumes:
  postgres_data:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:16-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    image: gazprom_backend
    build: .
    command: gunicorn --bind 0.0.0.0:${GUNICORN_PORT} hackathon_gazprom.wsgi:application
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  nginx:
    image: nginx:1.27.1-alpine
    volumes:
      - static_volume:/static
      - media_volume:/media
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - backend